rocket-ecommerce-v1.0.7/priv-rocket-ecommerce-main/core/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from drf_spectacular.views import SpectacularAPIView, SpectacularRedocView, SpectacularSwaggerView
from django.contrib.sitemaps.views import sitemap
from home.sitemaps import StaticSitemap, DynamicSitemap

sitemaps = {
    'static': StaticSitemap,
    'dynamic': DynamicSitemap
}

urlpatterns = [
    path("", include("home.urls")),
    path("admin/", admin.site.urls),
    # path("api/", include("apps.api.urls")),
    path("users/", include("apps.users.urls")),
    path("charts/", include("apps.charts.urls")),
    path("tables/", include("apps.tables.urls")),
    path("tasks/", include("apps.tasks.urls")),

    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}),

    path('api/docs/schema', SpectacularAPIView.as_view(), name='schema'),
    path('api/docs/'      , SpectacularSwaggerView.as_view(url_name='schema'), name='swagger-ui'),
    path("__debug__/", include("debug_toolbar.urls")),
]

urlpatterns += static(settings.CELERY_LOGS_URL, document_root=settings.CELERY_LOGS_DIR)
urlpatterns += static(settings.MEDIA_URL      , document_root=settings.MEDIA_ROOT     )

rocket-ecommerce-v1.0.7/priv-rocket-ecommerce-main/apps/common/models.py
from django.db import models
from django.contrib.auth.models import User
from decimal import Decimal
from django_quill.fields import QuillField
from autoslug import AutoSlugField
from django.urls import reverse

# Create your models here.

class BaseModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True

class Tag(BaseModel):
    name = models.CharField(max_length=255)
    slug = AutoSlugField(populate_from='name', unique=True)

    def __str__(self):
        return self.name

class ProductStripe(BaseModel):
    name = models.CharField(max_length=255)
    description = models.TextField(null=True, blank=True)
    image = models.ImageField(upload_to='stripe_product', null=True, blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return self.name


class Color(BaseModel):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

class Product(BaseModel):
    product_stripe = models.OneToOneField(ProductStripe, on_delete=models.CASCADE, related_name="product")
    name = models.CharField(max_length=255)
    slug = AutoSlugField(populate_from='name', unique=True)
    img_main = models.ImageField(upload_to='product', null=True, blank=True)
    img_1 = models.ImageField(upload_to='product', null=True, blank=True)
    img_2 = models.ImageField(upload_to='product', null=True, blank=True)
    img_3 = models.ImageField(upload_to='product', null=True, blank=True)
    img_4 = models.ImageField(upload_to='product', null=True, blank=True)
    img_5 = models.ImageField(upload_to='product', null=True, blank=True)
    url_video = models.URLField(null=True, blank=True)
    short_description = models.CharField(max_length=100, null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    tags = models.ManyToManyField(Tag, blank=True)
    stock = models.IntegerField(null=True, blank=True)
    featured = models.BooleanField(default=False)
    discount = models.DecimalField(max_digits=5, decimal_places=2, blank=True,null=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)

    def discounted_price(self):
        return round(self.price + (self.price * (self.discount / 100)), 2)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('product_details', kwargs={'slug': self.slug})




class Cart(BaseModel):
    color = models.ForeignKey(Color, on_delete = models.CASCADE, blank=True,null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    is_ordered = models.BooleanField(default=False)

    @property
    def total_price(self):
        if self.product.discount:
            discounted_price = self.product.discounted_price()
            return (discounted_price * self.quantity).quantize(Decimal('0.00'))
        else:
            return (self.product.price * self.quantity).quantize(Decimal('0.00'))
        
class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    cart = models.ManyToManyField(Cart)
    created_at = models.DateTimeField(auto_now_add=True, null = True, blank=True)

    class Meta:
        ordering = ['-created_at']
    
    def total_order(self):
        total_price = Decimal('0')
        for cart in self.cart.all():
            total_price += cart.total_price
        return total_price.quantize(Decimal('0.00'))
    


class StripeCredentials(BaseModel):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    publishable_key = models.CharField(max_length=255)
    secret_key = models.CharField(max_length=255)

# class ProductImage(BaseModel):
#     product = models.ForeignKey(Product, on_delete=models.CASCADE)
#     image = models.ImageField(upload_to='product')



class ProductProps(BaseModel):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name="product_props")
    prop = models.CharField(max_length=255)
    value = models.CharField(max_length=255)



class TypeChocies(models.TextChoices):
    site_name = 'site_name', 'Site name'
    copyright = 'copyright', 'Copyright'
    stripe_pub_key = 'stripe_pub_key', 'Stripe publishable key'
    stripe_sec_key = 'stripe_sec_key', 'Stripe secret key'
    social_twitter = 'social_twitter', 'Social twitter'
    social_instagram = 'social_instagram', 'Social instagram'
    social_github = 'social_github', 'Social github'
    social_facebook = 'social_facebook', 'Social facebook'
    legal_privacy = 'legal_privacy', 'Legal privacy'
    legal_terms = 'legal_terms', 'Legal terms'
    legal_help = 'legal_help', 'Legal help'
    hero_video = 'hero_video', 'Hero video'

class Settings(BaseModel):
    type = models.CharField(max_length=255, choices=TypeChocies.choices, unique=True)
    value = models.TextField(null=True, blank=True)
    value_html = QuillField(null=True, blank=True)
    file = models.FileField(upload_to='hero/', null=True, blank=True)

rocket-ecommerce-v1.0.7/priv-rocket-ecommerce-main/templates/pages/cart-list.html
{% extends "layouts/base-products.html" %}
{% load get_total %}

{% block content %}

  <section class="text-gray-700 body-font overflow-hidden bg-white border-b">
    <div class="max-w-screen-2xl mx-auto px-5 pt-52 md:pt-44 pb-10 md:pb-44">
      <div class="block md:grid md:grid-cols-5 gap-3">
        <div class="md:col-span-4 w-full md:w-11/12 mb-5 md:mb-0">
          <h3 class="text-3xl text-black font-medium mb-5">Cart</h3>

          <div class="relative overflow-x-auto sm:rounded-lg">
            <table class="w-full text-sm text-left rtl:text-right text-gray-500 dark:text-gray-400">
              <thead class="text-xs text-gray-700 uppercase bg-white dark:text-gray-400">
                <tr class="border-b">
                  <th scope="col" class="py-3 pr-56 md:pr-0">
                    Item
                  </th>
                  <th scope="col" class="py-3 pr-24 md:pr-0">
                    Quantity
                  </th>
                  <th scope="col" class="py-3 pr-10 md:pr-0">
                    Price
                  </th>
                  <th scope="col" class="py-3 pr-10 md:pr-0">
                    Total
                  </th>
                </tr>
              </thead>
              <tbody>
                {% for cart in carts %}
                <tr class="bg-white border-b bg-white">
                  <td class="py-4">
                    <div class="flex items-center gap-3">
                      <img src="{{ cart.product.img_main.url }}" class="block w-24 h-24 border rounded-lg object-cover" alt="Apple Watch">
                      <div>
                        <span class="block mb-2">{{ cart.product.name }}</span>
                      </div>
                    </div>
                  </td>
                  <td class="py-4 font-semibold text-gray-900 dark:text-white">
                    <div class="flex items-center gap-3">
                      <a href="{% url 'delete_cart' cart.id %}">
                        <svg class="w-6 h-6 text-gray-800 dark:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24">
                          <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 7h14m-9 3v8m4-8v8M10 3h4a1 1 0 0 1 1 1v3H9V4a1 1 0 0 1 1-1ZM6 7h12v13a1 1 0 0 1-1 1H7a1 1 0 0 1-1-1V7Z"/>
                        </svg>
                      </a>
                      <form method="post" action="{% url "update_cart_quantity" cart.id %}" class="cart-form max-w-sm">
                        {% csrf_token %}

                        <select name="quantity" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500">
                          {% for value in 10|times %}
                            <option {% if value == cart.quantity %} selected {% endif %} value="{{ value }}">{{ value }}</option>
                          {% endfor %}
                        </select>
                      </form>   
                    </div>                 
                  </td>
                  <td class="py-4">
                    €{{ cart.product.price }}
                  </td>
                  <td class="py-4 font-semibold text-gray-900 dark:text-white">
                    €{{ cart.total_price }}
                  </td>
                </tr>
                {% endfor %}
              </tbody>
            </table>
          </div>

        </div>

        <div>
          <h3 class="text-3xl text-black font-medium mb-5">Summary</h3>
          <hr class="mb-5">
          <div class="mb-5">
            <div class="flex justify-between mb-3 text-sm font-normal">
              <span class="block">Subtotal</span>
              <span class="block">€{{ carts|get_total }}</span>
            </div>
            <div class="flex justify-between mb-3 text-sm font-normal">
              <span class="block">Shipping</span>
              <span class="block">€1.99</span>
            </div>
            <div class="flex justify-between mb-3 text-sm font-normal">
              <span class="block">Taxes</span>
              <span class="block">€0.00</span>
            </div>
          </div>
          <hr class="mb-5">
          <div class="mb-5">
            <div class="flex justify-between mb-3 text-sm font-normal">
              <span class="block">Total</span>
              <span class="block text-xl font-medium text-black">€{{ carts|get_total:"1.99" }}</span>
            </div>
          </div>
          <hr class="mb-5">
          <a class="w-full text-white bg-[#050708] hover:bg-[#050708]/90 focus:ring-4 focus:outline-none focus:ring-[#050708]/50 font-medium rounded-lg text-sm px-5 py-3 text-center inline-flex items-center justify-center dark:focus:ring-[#050708]/50 dark:hover:bg-[#050708]/30 me-2 mb-2" href="{% url "create_checkout_session" %}">Go to checkout</a>
        </div>
      </div>
    </div>
  </section>

{% endblock %}

{% block extra_js %}

<script>
  document.querySelectorAll('.cart-form select').forEach(function(select) {
      select.addEventListener('change', function() {
          this.parentNode.submit();
      });
  });
</script>

{% endblock extra_js %}

rocket-ecommerce-v1.0.7/priv-rocket-ecommerce-main/templates/pages/category-list.html
{% extends "layouts/base-products.html" %}

{% block content %}

<div class="py-44 border-b">
    <div class="max-w-screen-2xl mx-auto">
        <div class="flex items-center justify-center mb-5 mt-5">
            <hr class="border-t border-gray-300 flex-grow mr-4">
            <h1 class="text-xl font-semibold text-center text-gray-600">Categories</h1>
            <hr class="border-t border-gray-300 flex-grow ml-4">
        </div>
        <div class="grid grid-cols-2 md:grid-cols-4 gap-4">
            {% for tag in tags %}
            <a href="{% url 'category_products' tag.slug %}" class="inline-flex items-center px-5 py-2.5 text-sm font-medium text-center text-white bg-blue-700 rounded-lg hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">
                <span class="mr-2">{{ tag.name }}</span>
                <span class="inline-flex items-center justify-center w-4 h-4 text-xs font-semibold text-blue-800 bg-blue-200 rounded-full">{{ tag.product_count }}</span>
            </a>
            {% endfor %}
        </div>
    </div>
</div>

{% endblock %}

rocket-ecommerce-v1.0.7/priv-rocket-ecommerce-main/templates/pages/category-products.html
{% extends "layouts/base-products.html" %}

{% block title %}
    {{ tag.product_set.all|length }} | {{ copyright }} 
{% endblock title %}

{% block content %}

<section class="bg-white pt-0 {% if not request.path == '/' %} md:pt-44 {% else %} md:pt-10 {% endif %} md:pt-10 mb-10 md:mb-16 pb-10 md:pb-16 border-b border-gray-200">
  <div class="mt-10">
      <div class="grid mx-auto max-w-screen-2xl gap-14 lg:grid-cols-3 px-5" id='scrollTarget'>
          {% for product in tag.product_set.all %}
              {% if not product.discount %}
              <a class="group" href="{% url 'product_details' product.slug %}">
                  <div class="max-w-full mx-auto bg-white rounded-lg overflow-hidden border border-gray-200 md:h-[570px]">
                      {% if product.img_main %}
                          <img class="rounded-t-lg h-full object-cover" src="{{ product.img_main.url }}" alt="product image" />
                      {% endif %}
                  </div>
                  <div class="flex justify-between mt-5">
                      <span class="block text-sm text-slate-700">{{ product.name }}</span>
                      <span class="block text-sm text-slate-500">€{{ product.price }}</span>
                  </div>
              </a>
              {% else %}
              <a class="group" href="{% url 'product_details' product.slug %}">
                  <div class="max-w-full mx-auto bg-white rounded-lg overflow-hidden border border-gray-200 md:h-[570px] relative">
                      {% if product.img_main %}
                          <img class="rounded-t-lg h-full object-cover" src="{{ product.img_main.url }}" alt="product image" />
                      {% endif %}
                      <div class="absolute top-2 right-2">
                        {% if product.discount %}
                        <div class="bg-red-400 text-white rounded-md py-1 px-2">
                            
                          <span class="text-xl">-{{ product.discount|floatformat:"0" }}%</span>
                          
                        </div>
                        {% endif %}
                      </div>
                  </div>
                  <div class="flex justify-between mt-5">
                      <span class="block text-sm text-slate-700">{{ product.name }}</span>
                      <div class="flex gap-3">
                        <span class="block text-sm text-slate-500">€{{ product.price }}</span>
                        <span class="block text-sm text-slate-500 line-through">€{{ product.discounted_price }}</span>
                      </div>
                  </div>
              </a>
              {% endif %}
          {% endfor %}
      </div>
  </div>
</section>  

{% endblock %}

rocket-ecommerce-v1.0.7/priv-rocket-ecommerce-main/templates/pages/discounted-product.html
<!-- discounted_product_list.html -->

{% extends "layouts/base-products.html" %}

{% block title %}
  Discounts - {{ products|length }} products | {{ copyright }} 
{% endblock title %}

{% block content %}


<section class="bg-white pt-44 md:pt-16 mb-10 md:mb-16 pb-10 md:pb-40 border-b border-gray-200">
  <div class="md:mt-28 mt-10">
      <div class="grid mx-auto max-w-screen-2xl gap-14 lg:grid-cols-3 px-5" id='scrollTarget'>
          {% for product in products %}
          <a class="group" href="{% url 'product_details' product.slug %}">
              <div class="max-w-full mx-auto bg-white rounded-lg overflow-hidden border border-gray-200 md:h-[570px] relative">
                  {% if product.img_main %}
                      <img class="rounded-t-lg h-full object-cover" src="{{ product.img_main.url }}" alt="product image" />
                  {% endif %}
                  <div class="absolute top-2 right-2">
                    {% if product.discount %}
                    <div class="bg-red-400 text-white rounded-md py-1 px-2">
                        
                      <span class="text-xl">-{{ product.discount|floatformat:"0" }}%</span>
                      
                    </div>
                    {% endif %}
                  </div>
              </div>
              <div class="flex justify-between mt-5">
                  <span class="block text-sm text-slate-700">{{ product.name }}</span>
                  <div class="flex gap-3">
                    <span class="block text-sm text-slate-500">€{{ product.price }}</span>
                    <span class="block text-sm text-slate-500 line-through">€{{ product.discounted_price }}</span>
                  </div>
              </div>
          </a>
          {% endfor %}
      </div>
  </div>
</section>  


{% endblock %}

rocket-ecommerce-v1.0.7/priv-rocket-ecommerce-main/templates/pages/edit-image.html
{% extends "layouts/base.html" %}
{% load static %}

{% block extrastyle %}

<link rel="stylesheet" href="{% static "assets/cropper.css" %}">

{% endblock extrastyle %}

{% block content %}

<section class="max-w-xl mx-auto my-10">
    <h6 class="text-lg font-bold dark:text-white mb-3">Original Image: </h6>
    <div class="flex items-end gap-3 mb-5">
        <div>
            <img id="image" class="" src="{{ image_path.url }}" alt="">
        </div>
        <div>
            <button class="focus:outline-none text-white bg-red-700 hover:bg-red-800 focus:ring-4 focus:ring-red-300 font-medium rounded-lg text-sm px-5 py-2.5 me-2 mb-2 dark:bg-red-600 dark:hover:bg-red-700 dark:focus:ring-red-900 mb-3" id="cropButton">Crop</button>
            <a href="{% url "edit_product" product.id %}" class="text-white bg-gray-800 hover:bg-gray-900 focus:outline-none focus:ring-4 focus:ring-gray-300 font-medium rounded-lg text-sm px-5 py-2.5 me-2 mb-2 dark:bg-gray-800 dark:hover:bg-gray-700 dark:focus:ring-gray-700 dark:border-gray-700">Cancel</a>
        </div>
    </div>   
    <form id="cropped_image_section" class="hidden" method="post">
        {% csrf_token %}
        <h6 class="text-lg font-bold dark:text-white mb-3">Cropped Image: </h6>
        <input type="hidden" id="cropped_image" name="{{ img_name }}">
        <img id="cropped_image_preview" src="" alt="">
        <button class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 me-2 mb-2 mt-2 dark:bg-blue-600 dark:hover:bg-blue-700 focus:outline-none dark:focus:ring-blue-800" type="submit">Save</button>
    </form> 
</section>

{% endblock content %}

{% block extra_js %}

<script src="https://cdnjs.cloudflare.com/ajax/libs/cropperjs/1.6.1/cropper.min.js"></script>

<script>
    const image = document.getElementById('image');
    const croppedImage = document.getElementById('cropped_image_preview');
    const croppedImageValue = document.getElementById('cropped_image');
    const cropper = new Cropper(image, {
        aspectRatio: 16 / 9,
        crop(event) {
        },
    });

    const cropButton = document.getElementById('cropButton');
    const croppedImageSection = document.getElementById('cropped_image_section');
    cropButton.addEventListener('click', function() {
        const canvas = cropper.getCroppedCanvas();
        if (!canvas) {
            return;
        }

        croppedImage.classList.remove('hidden');
        croppedImageSection.classList.remove('hidden');
        croppedImage.src = canvas.toDataURL();
        croppedImageValue.value = canvas.toDataURL();
        
    });
</script>

{% endblock extra_js %}

rocket-ecommerce-v1.0.7/priv-rocket-ecommerce-main/templates/pages/help.html
{% extends "layouts/base-products.html" %}
{% load static %}

{% block title %}
    Help - Learn how to use Rocket eCommerce | {{ copyright }}
{% endblock title %}

{% block content %}

<section class="pt-52 md:pt-44 border-b border-gray-200">
    <div class="max-w-screen-2xl mx-auto px-5 mb-10">
        <h3 class="text-3xl font-bold dark:text-white mb-3">Help</h3>
        {{ legal_help.html|safe }}
    </div>
</section>

{% endblock content %}

rocket-ecommerce-v1.0.7/priv-rocket-ecommerce-main/templates/pages/payment-success.html
{% extends "layouts/base-products.html" %}



{% block content %}



<div class="bg-green-200 h-screen flex items-center justify-center">
    <div class="text-center">
        <div class="bg-green-500 text-white p-4 rounded-full inline-block">
            <svg class="w-6 h-6 text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
                <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m5 12 4.7 4.5 9.3-9"/>
              </svg>
        </div>
        <h1 class="text-3xl mt-4">Payment Successful!</h1>
        <p class="text-lg">Thank you for your purchase. Your payment was successful.</p>
        <!-- Additional content or redirection logic can be added here -->
    </div>
</div>



{% endblock  %}

rocket-ecommerce-v1.0.7/priv-rocket-ecommerce-main/templates/pages/search-page.html
{% extends "layouts/base-products.html" %}
{% load static %}

{% block title %}
    Search for {{ search|title }} - {{ products|length }} products | {{ copyright }} 
{% endblock title %}

{% block content %}

<section class="max-w-screen-2xl mx-auto px-5 py-44">
    {% for product in products %}
    <a href="{% url "product_details" product.slug %}" class="flex items-center gap-5 border-b py-5 hover:border-r-8 hover:border-r-lime-700">
        <img class="block w-24 h-24 object-cover" src="{{ product.img_main.url }}" alt="">
        <div>
            <span class="uppercase font-normal flex gap-5">
                {% for tag in product.tags.all %}
                    <span>{{ tag.name }}</span>
                {% endfor %}
            </span>
            <h4 class="text-xl uppercase font-medium">{{ product.name }}</h4>
        </div>
    </a>
    {% endfor %}
</section>

{% endblock content %}

rocket-ecommerce-v1.0.7/priv-rocket-ecommerce-main/templates/pages/transaction.html
{% extends "layouts/base.html" %}
{% load static %}

{% block messages %}

{% if messages %}
    {% for message in messages %}
        <div class="flex items-center p-4 text-sm rounded-lg dark:bg-gray-800 {{message.tags}}" role="alert">
            <svg class="flex-shrink-0 inline w-4 h-4 mr-3" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
                <path d="M10 .5a9.5 9.5 0 1 0 9.5 9.5A9.51 9.51 0 0 0 10 .5ZM9.5 4a1.5 1.5 0 1 1 0 3 1.5 1.5 0 0 1 0-3ZM12 15H8a1 1 0 0 1 0-2h1v-3H8a1 1 0 0 1 0-2h2a1 1 0 0 1 1 1v4h1a1 1 0 0 1 0 2Z"/>
            </svg>
            <span class="sr-only">Info</span>
            <div>{{ message }}</div>
        </div>
    {% endfor %}
{% endif %}


{% endblock messages %}


{% block content %}

<div class="m-5 bg-white dark:bg-gray-900 shadow-md rounded-lg overflow-hidden ">

<div class="relative overflow-x-auto shadow-md sm:rounded-lg">
    <table class="w-full text-sm text-left rtl:text-right text-gray-500 dark:text-gray-400">
        <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
            <tr>
                <th scope="col" class="px-6 py-3">
                    Customer
                </th>
                <th scope="col" class="px-6 py-3">
                    Payment Method
                </th>
                <th scope="col" class="px-6 py-3">
                    Amount
                </th>
                <th scope="col" class="px-6 py-3">
                    Status
                </th>
                
            </tr>
        </thead>
        <tbody>
            {% for charge in charges %}
            <tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700 hover:bg-gray-50 dark:hover:bg-gray-600">
                <th scope="row" class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white">
                    {{ charge.customer_name }}
                </th>
                <td class="px-6 py-4">
                    {{ charge.payment_method_details.card.brand }} * * * {{ charge.payment_method_details.card.last4 }}
                </td>
                <td class="px-6 py-4">
                    {{ charge.amount|floatformat:"2" }}
                </td>
                <td class="px-6 py-4">
                    {{ charge.status }}
                </td>
                
            </tr>
            {% endfor %}
            
        </tbody>
    </table>
</div>
</div>

{% endblock content %}